CREATE TABLE TBL_CONTATO(
    ID_CONTATO NUMERIC(4) PRIMARY KEY,
    NOME_CONTATO VARCHAR2(50) NOT NULL,
    CELULAR_CONTATO VARCHAR2(11) NOT NULL,
    EMAIL_CONTATO VARCHAR2(60) NOT NULL,
    INSTAGRAM VARCHAR2(50),
    TIPO VARCHAR2(20)
);

SELECT * FROM CONTATO;

CREATE TABLE TBL_ENDERECO(
	IDENDERECO NUMERIC(5) PRIMARY KEY,
	CEP VARCHAR2(8),
	RUA VARCHAR2(60),
	COMPLEMENTO VARCHAR2(20),
	BAIRRO VARCHAR2(100),
	CIDADE VARCHAR2(20),
	UF VARCHAR2(2),
	NUMERO VARCHAR2(5)
)


alter table tbl_endereco modify bairro varchar2(100)

SELECT * FROM TBL_ENDERECO WHERE IDENDERECO = 1