/*  Nome: Felipe Menezes Prometti – RM: 555174
    Nome: Murillo Ari Sant'Anna – RM: 557183
    Nome: Samuel Damasceno - RM: 558876
    Nome: Vitor Isac Belicci - RM: 554686
    Tema sorteado: Ferramentas e construção
*/

package Models.Enums;

public enum CategoriaProduto {
    ACESSORIOS_DE_FERRAMENTAS,
    VENTILADORES_DE_TETO,
    FERRAMENTAS_DE_MEDICAO,
    CASA_INTELIGENTE,
    FERRAMENTAS_ELETRICAS,
    ELETRICA,
    FERRAMENTAS_MANUAIS,
    ENCANAMENTO_BRUTO,
    FERRAMENTAS_PNEUMATICAS,
    ESCADAS,
    FURADEIRAS,
    FERRAGENS,
    ORGANIZADOR_DE_FERRAMENTAS,
    ILUMINACAO,
    PARAFUSADEIRA_ELETRICA,
    INSTALACOES_DE_COZINHA_BANHEIRO,
    MATERIAL_DE_PINTURA,
    PROTECAO_E_SEGURANCA;
}